# Generated by Django 4.2.5 on 2023-09-23 13:06

import blog.models
from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_blogpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", wagtail.blocks.CharBlock(form_classname="title")),
                    ("paragraph", wagtail.blocks.RichTextBlock()),
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                    (
                        "code",
                        wagtail.blocks.StructBlock(
                            [("code", wagtail.blocks.TextBlock())]
                        ),
                    ),
                    ("raw_html", blog.models.RawHTMLBlock()),
                ],
                use_json_field=True,
            ),
        ),
    ]
