# Generated by Django 3.2.22 on 2023-11-18 10:42

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('blog', '0003_alter_blogpage_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicTOCPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('dynamic_content', wagtail.fields.RichTextField(blank=True, verbose_name='Dynamic Content')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
