# Generated by Django 3.2.22 on 2023-11-18 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0005_alter_formsubmission_form_data'),
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('wagtailredirects', '0008_add_verbose_name_plural'),
        ('blog', '0005_alter_dynamictocpage_dynamic_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DynamicTOCPage',
        ),
    ]
