# Generated by Django 4.2.7 on 2023-12-16 09:04

import blog.models
from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_dynamictocpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", wagtail.blocks.CharBlock(form_classname="title")),
                    ("paragraph", wagtail.blocks.RichTextBlock()),
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                    (
                        "code",
                        wagtail.blocks.StructBlock(
                            [("code", wagtail.blocks.TextBlock())]
                        ),
                    ),
                    ("raw_html", blog.models.RawHTMLBlock()),
                    (
                        "publication",
                        wagtail.blocks.StructBlock(
                            [("title", wagtail.blocks.CharBlock())]
                        ),
                    ),
                ],
                use_json_field=True,
            ),
        ),
    ]
