# Generated by Django 4.2.7 on 2023-12-30 16:02

import blog.models
from django.db import migrations, models
import wagtail.blocks
import wagtail.contrib.typed_table_block.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_alter_blogpage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="content_choice",
            field=models.CharField(
                choices=[("choice_one", "Choice One"), ("choice_two", "Choice Two")],
                default="choice_one",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", wagtail.blocks.CharBlock(form_classname="title")),
                    ("paragraph", wagtail.blocks.RichTextBlock()),
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                    (
                        "code",
                        wagtail.blocks.StructBlock(
                            [("code", wagtail.blocks.TextBlock())]
                        ),
                    ),
                    ("raw_html", blog.models.RawHTMLBlock()),
                    (
                        "publication",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock()),
                                (
                                    "linked_page",
                                    wagtail.blocks.PageChooserBlock(
                                        help_text="Select a linked page", required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "table",
                        wagtail.contrib.typed_table_block.blocks.TypedTableBlock(
                            [
                                ("text", wagtail.blocks.CharBlock()),
                                ("numeric", wagtail.blocks.FloatBlock()),
                                ("rich_text", wagtail.blocks.RichTextBlock()),
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    "country",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("be", "Belgium"),
                                            ("fr", "France"),
                                            ("de", "Germany"),
                                            ("nl", "Netherlands"),
                                            ("pl", "Poland"),
                                            ("uk", "United Kingdom"),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                use_json_field=True,
            ),
        ),
    ]
