# Generated by Django 4.2.2 on 2024-01-04 10:48

import blog.models
from django.db import migrations
import wagtail.blocks
import wagtail.contrib.typed_table_block.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0011_alter_blogpage_body_alter_blogpage_content_choice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", wagtail.blocks.CharBlock(form_classname="title")),
                    ("paragraph", wagtail.blocks.RichTextBlock()),
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                    (
                        "code",
                        wagtail.blocks.StructBlock(
                            [("code", wagtail.blocks.TextBlock())]
                        ),
                    ),
                    ("raw_html", blog.models.RawHTMLBlock()),
                    (
                        "publication",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock()),
                                (
                                    "linked_page",
                                    wagtail.blocks.PageChooserBlock(
                                        help_text="Select a linked page", required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "table",
                        wagtail.contrib.typed_table_block.blocks.TypedTableBlock(
                            [
                                ("text", wagtail.blocks.CharBlock()),
                                ("numeric", wagtail.blocks.FloatBlock()),
                                ("rich_text", wagtail.blocks.RichTextBlock()),
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    "country",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("be", "Belgium"),
                                            ("fr", "France"),
                                            ("de", "Germany"),
                                            ("nl", "Netherlands"),
                                            ("pl", "Poland"),
                                            ("uk", "United Kingdom"),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "fixed_table",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "nation",
                                    wagtail.blocks.CharBlock(
                                        help_text="Enter nation", required=True
                                    ),
                                ),
                                (
                                    "capital",
                                    wagtail.blocks.CharBlock(
                                        help_text="Enter capital", required=True
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                use_json_field=True,
            ),
        ),
    ]
