# Generated by Django 4.2.5 on 2023-09-26 19:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wiki_similar_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wikipage",
            old_name="content",
            new_name="body",
        ),
    ]
