# Generated by Django 4.2.5 on 2023-09-26 20:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wiki_similar_app", "0002_rename_content_wikipage_body"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wikipage",
            old_name="body",
            new_name="content",
        ),
    ]
