# Generated by Django 4.2.2 on 2023-06-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaCertificativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_certificazione', models.CharField(max_length=300, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Schema Certificativo',
            },
        ),
        migrations.CreateModel(
            name='Auditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_auditor', models.CharField(max_length=300, unique=True)),
                ('email_auditor', models.EmailField(max_length=254)),
                ('disponibile', models.BooleanField(default=True)),
                ('foto', models.FileField(blank=True, default='default.jpg', upload_to='')),
                ('schema_certificativo', models.ManyToManyField(to='sgq.schemacertificativo')),
            ],
            options={
                'verbose_name': 'Auditor',
                'verbose_name_plural': 'Auditor',
            },
        ),
    ]
