# Generated by Django 4.2.2 on 2024-01-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sgq", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FixedTableContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nation", models.CharField(max_length=255)),
                ("capital", models.CharField(max_length=255)),
            ],
        ),
    ]
